### ISSUE TITLE
Resize panels In script editor

### ISSUE THREAD

**Issue by jdanish** [theRAPTLab/gsgo#749]
Right now it appears the line editor on the right is about 1/3 of the total size. We think 1/2 would be more usable. Long-term it'd be great if we could just re-size this, but if that's a major undertaking then changing the size to be 1/2 would be great.

**Comment by benloh** [comment]
@jdanish screenshots and urls in cases like this would save many hours of hunting for what you are referring to...

**Comment by jdanish** [comment]
Of course - let me know of any like this and I'll add.

![Image](https://github.com/theSTEPproject/gsgo/assets/5529898/0c309dfe-4703-4421-aaec-2f7d61e4cd4e)

**Comment by benloh** [comment]
@jdanish I think the challenge here is figuring out what to do with long lines in the script editor: wrapping them makes them hard to read, and using a scrollbar is difficult for everyone.  That's the main reason why it's as wide as it is.

I suppose another method would be to close or reduce the size of the edit panel on the right until something is selected.

Estimate: 2 if simply change sizes based on selection/edit state
Estimate: 4-8 if add a dragger.

**Comment by jdanish** [comment]
When I tested, the script panel currently does scroll if needed - it just requires the mousepad in my case, and there is no scroll bar. I guess let's try the simpler one and see how that works?

**Comment by benloh** [comment]
Yeah I'm curious if you saw how students dealt with that (if at all).  Did using chromebooks teach most students how to scroll horizontally?  What about if they're only using a mouse (if that is even still a possibility in this day and age)?

**Comment by benloh** [comment]
Implemented with #761
