### ISSUE TITLE
Character controller offset on 2nd character and beyond

### ISSUE THREAD

**Issue by jdanish** [theRAPTLab/gsgo#765]
In the most recent builds, there is a weird bug with the character controller 1 and 2 (not 3). See attached. The first character works fine. The 2nd and beyond shift right of the cursor for some reason.

https://github.com/theRAPTLab/gsgo/assets/5529898/08d6011d-ba72-43c9-a34e-82325e3921a6

**Comment by benloh** [comment]
@jdanish was this always the case?  I don't remember seeing this before?
I know there have been some changes to events in browsers.  I wonder if that's the source...

**Comment by jdanish** [comment]
No, this is a new problem and weirdly does not occur in character controller 3, the one I hacked using your old code.

**Comment by jdanish** [comment]
I'm going to close this actually since we all now prefer controller 3, so we can remove 1 and 2.
