### ISSUE TITLE
Selecting a line in the wizard scrolls it to the top

### ISSUE THREAD

**Issue by jdanish** [theRAPTLab/gsgo#768]
Open the wizard. Select a line mid-way down the screen. The screen flashes and the line being edited is now just below the top.

Moving it after selection is confusing. Can we leave it where it is?

**Comment by benloh** [comment]
Gah. I had to do that to get the code to scroll when selecting a bookmark.  I'll have to figure out how to differentiate that.

**Comment by benloh** [comment]
Should be fixed in #763 with 34855b8b59c4f3a923846473319d2c8fd200b348.

@jdanish please verify this is fixed and close.
