### ISSUE TITLE
Integrate a simple color picker for setting colors and colorization in the characters

### ISSUE THREAD

**Issue by jdanish** [theRAPTLab/gsgo#779]
A basic general color picker works for this. No need to get fancy.

**Comment by benloh** [comment]
@jdanish 
It ends up the standard HTML input element does have a color option.  However, it only supports hex and no alpha.  Click on the color in the "Choose your monster's color" on [this mdn page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color) to see an example.

> Note: Setting the value to anything that isn't a valid, fully-opaque, RGB color in hexadecimal notation will result in the value being set to #000000. In particular, you can't use CSS's standardized color names, or any CSS function syntax, to set the value. This makes sense when you keep in mind that HTML and CSS are separate languages and specifications. In addition, colors with an alpha channel are not supported; specifying a color in 9-character hexadecimal notation (e.g. #009900aa) will also result in the color being set to #000000.

I'm guessing for the color picker you want the ability to pick swatches?  And define a basic palette?  Or is super simple color picker adequate?

**Comment by jdanish** [comment]
This is adequate, thanks. I think in GEM-STEP, just so long as we can pick a color we are good to go, and kids can see the colors so won't need names. Alpha can be handled separately. For some of the other tools we might want swatches (e.g., Net.Create) but this works for me!

**Comment by benloh** [comment]
Implemented with #797
