### ISSUE TITLE
introduce a `# TAG` setting e.g. `# TAG isPozyxDefault`

### ISSUE THREAD

**Issue by jdanish** [theRAPTLab/gsgo#784]
Might be more intuitive to have it as a project-level setting similar to bg color, but I am fine with whatever is easiest.

**Comment by benloh** [comment]
True, but then things start to break if the character name changes.  Plus the default selection code is already `TAG` based.  But I'll take a look to see what is more efficient.

**Comment by jdanish** [comment]
Fair point. Either isn't that hard, so go for quick to implement in this case and we can revisit later if needed. Thanks!

**Comment by benloh** [comment]
Implemented with #802
